apiVersion: v1
kind: Pod
metadata:
 name: reward-program-web-1.0.5
 labels:
  app: reward-program-web
  release: "1.0.5"
spec:
 containers:
 - name: reward-program-web
   image: fapinheiro/reward-program-web:1.0.5

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#  name: reward-program-web-1.0.3
#  labels:
#   app: reward-program-web
#   release: "1.0.3"
# spec:
#  containers:
#  - name: reward-program-web
#    image: fapinheiro/reward-program-web:1.0.3